name: Publish Mod

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: List build directory
        run: ls -l build/libs
      - name: Publish mod
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: KwrF4Ziw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs/*.jar
          name: ${{ github.ref_name }}
          version: ${{ github.ref_name }}
          changelog-file: CHANGELOG.md
          loaders: fabric
          game-versions: 1.21.2
          fail-mode: warn
