name: Publish Mod and Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :fabric:build :paper:shadowJar

      - name: Publish Fabric Mod to Modrinth and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: KwrF4Ziw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: fabric/build/libs/!(*-@(dev|sources)).jar
          name: "IDoTheBlacklist Fabric ${{ github.ref_name }}"
          version: ${{ github.ref_name }}
          changelog-file: README.md
          loaders: fabric
          game-versions: 1.21.2

      - name: Publish Paper Plugin to Modrinth and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: KwrF4Ziw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: fabric/build/libs/!(*-@(dev|sources)).jar
          name: "IDoTheBlacklist Paper ${{ github.ref_name }}"
          version: ${{ github.ref_name }}
          changelog-file: README.md
          loaders: paper
          game-versions: 1.21

      - name: Publish Paper Plugin to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: paper/build/libs/IDoTheBlacklist-Paper-${{ github.ref_name }}.jar
          name: "IDoTheBlacklist Paper ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}