name: IDoTheBlacklist-Paper
version: ${version}
main: net.idothehax.idotheblacklist.paper.IDoTheBlacklist
api-version: '1.21'
author: IDoTheHax
description: The Blacklist aims to ban troublesome players across networks that use this mod, Proudly uses IDoTheAPI
commands:
  setapikey:
    description: Sets the API key for the blacklist service
    usage: /setapikey <key>